Use clusterName to compute replica node affinity
renderinc/postgres-operator pull request #1
Opened 2020-10-29 01:39 UTC by joshi4

2020-10-29 02:41 UTC, aduong approved these changes

2020-10-29 17:36 UTC, wendorf requested changes
Should this commit be based on `render-master` instead of `master`?

2020-10-29 17:36 UTC, wendorf commented on operator/cluster/cluster_strategy_1.go
> +	"os"
This import should be moved up, and we should probably get rid of that commented-out import.

2020-10-29 19:23 UTC, aduong commented
Didn't even notice the master v render-master, but yes, it should be render-master.

2020-10-30 00:04 UTC, joshi4 commented on operator/cluster/cluster_strategy_1.go
> +	"os"
this was resolved when changing the branch from master to render-master.

2020-10-30 00:24 UTC, wendorf approved these changes
🦷

2020-11-03 02:49 UTC, joshi4 commented
I've tested this operator locally in my dev environment and could create/suspend/resume databases as usual. Going to merge this in now.

2020-11-03 02:49 UTC, merged